version: '3.9'

services:
  colyseus:
    build: .
    ports:
      - 2567:2567
    restart: unless-stopped
    depends_on:
      - caddy

  caddy:
    image: caddy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  default:
    driver: bridge